fix: update footer to not be fixed to bottom of viewport
amlan-roy/resume-craft pull request #52
Opened 2024-02-11 14:59 UTC by tusharwebd

Issue: #48

# Summary

This fixes issue #48

## Requirement:

The footer is fixed at bottom of viewport and overlaps the other elements. We want them to be at the bottom of the whole page, not fixed to the bottom of the viewport.

## Changes made:

Added tailwind classes to ensure main component takes 100% of viewport and used `flex` classes to convert component into flex containers.

## How Has This Been Tested?

### Screenshots / Videos 

https://github.com/amlan-roy/resume-craft/assets/65904813/dfb2ab01-1a92-4735-8307-2205dc31ce3c

## Checklist:

- [] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-02-11 15:56 UTC, tusharwebd commented
I see unit tests failed. Let me check on this.

2024-02-11 16:00 UTC, amlan-roy commented on src/app/layout.tsx
This works. However, I would suggest using `cn()` function from "@/lib/utils" for consistency here.

You can use something like 
`className={cn(inter.className, "min-h-screen flex flex-col")}`

2024-02-11 16:05 UTC, amlan-roy requested changes
We would also need to add `className="flex-grow"` in all the `layout.tsx` files (except the`src\app\layout.tsx` file). Otherwise, the footer would not be pushed down if the height of the main content does not cover the full screen. You can refer the [deployment ](https://resume-craft-git-fork-tusharwebd-foo-1c7ec7-amlan-roys-projects.vercel.app/home)of this branch to see this behaviour.

2024-02-11 16:07 UTC, amlan-roy commented on src/app/layout.tsx
When making changes for this, I would also suggest updating the structure of the elements as detailed in the issue description. Thanks.

2024-02-11 16:07 UTC, tusharwebd commented
> We would also need to add `className="flex-grow"` in all the `layout.tsx` files (except the`src\app\layout.tsx` file). Otherwise, the footer would not be pushed down if the height of the main content does not cover the full screen. You can refer the [deployment ](https://resume-craft-git-fork-tusharwebd-foo-1c7ec7-amlan-roys-projects.vercel.app/home)of this branch to see this behaviour.

Makes sense. Checking on this.

2024-02-11 16:17 UTC, tusharwebd commented
@amlan-roy, I've requested access for the vercel deployment.

2024-02-12 12:17 UTC, amlan-roy commented on src/app/layout.tsx
Made the changes

2024-02-12 12:19 UTC, amlan-roy approved these changes
LGTM! 🚀
Made the remaining changes since it is required for the ongoing changes. Thanks for the efforts @tusharwebd.

2024-02-12 12:20 UTC, merged